### ISSUE TITLE
`localhost` URLs not recognized as valid

### ISSUE THREAD

**Issue by jeffgore00** [retextjs/retext-syntax-urls#1]
Very common in a README, I would think, to point the developer to a localhost URL.

Example: `http://localhost:3000/home`

Perhaps this is more of an issue with retext in general, but I am using it in the context of this package with `retext-spell`:
https://github.com/tbroadley/spellchecker-cli

**Comment by wooorm** [comment]
Def common, sounds like something that should be supported.
Is that something you could investigate?

**Comment by jeffgore00** [comment]
Sure thing, I'll take a closer look at the codebase and can raise a PR if needed.

**Comment by jeffgore00** [comment]
@wooorm I looked at `index.js` for over half an hour, threw in a bunch of console.logs, and to be honest, I still have no idea how this works. 

I think I would need to get more deeply into `retext` in general to understand how this function has so much logic and returns an integer rather than performs a regex match. There does seem to be a couple different points that need to be edited (URL is at end of sentence vs. beginning or middle of sentence).

So, with that said, I'm punting it back to the you and maintainers here who would likely be able to fix this in 5% of the time it would take me. I would take a look at whatever PR you raise to learn about how this works.

**Comment by wooorm** [comment]
Fixed!
