### ISSUE TITLE
Issue with parsing on-premise URLs

### ISSUE THREAD

**Issue by dmsehuang** [retextjs/retext-syntax-urls#3]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.1.1

### Steps to reproduce

The plugin fails to parse on-premise URL. Example:

```js
import { unified } from "unified";
import retextEnglish from "retext-english";
import retextSyntaxUrls from "retext-syntax-urls";
import { visit } from 'unist-util-visit';
import { inspect } from 'unist-util-inspect';

const content = 'on-premise URL: https://CorporateIntranet/page.aspx'
const processor = unified()
            .use(retextEnglish)
            .use(retextSyntaxUrls);
const tree = processor.parse(content);
console.log(inspect(tree));
```

### Expected behavior

The source node should be: https://CorporateIntranet/page.aspx

### Actual behavior

The source node is: page.aspx

**Comment by wooorm** [comment]
Hey!

You’re welcome to try and change the algorithm, but it will likely be extremely hard (I looked at it just now and there’s no simple way).

This plugin looks for a TLD, say, `example.com`. It doesn’t require protocols or paths. It allows many many things around it (e.g., it also parses email addresses). Removing that would turn every word into a URL.

Closing as I think it’s a trade off.

**Comment by dmsehuang** [comment]
Thanks @wooorm for the comment.

I found some other issues:

Issue 1:
```
const content = 'Incorrect source node (e.g. Example)';
```

Expected behavior: no source node should be found
Actual behavior: source node is '(e.g'

Issue 2:
```
const content = '(e.g. Example)';
```

Expected behavior: syntax tree should be built at least.
Actual behavior: TypeError: Cannot read properties of undefined (reading 'type')

---
Did I misuse the plugins? 

Thanks
