### ISSUE TITLE
Issue with parenthesis

### ISSUE THREAD

**Issue by dmsehuang** [retextjs/retext-syntax-urls#4]
### Initial checklist

- [X] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.1.1

### Steps to reproduce

```js
import { unified } from "unified";
import retextEnglish from "retext-english";
import retextSyntaxUrls from "retext-syntax-urls";
import { visit } from 'unist-util-visit';
import { inspect } from 'unist-util-inspect';

const content = 'Incorrect source node (e.g. dmeshuang@yahoo.com)'
const processor = unified()
            .use(retextEnglish)
            .use(retextSyntaxUrls);
const tree = processor.parse(content);
console.log(inspect(tree));
```

The bug is described below.

In addition, if I change the content to:
```js
const content = '(e.g. dmeshuang@yahoo.com)'
```
The library will give an exception saying that: 'TypeError: Cannot read properties of undefined (reading 'type')'

### Expected behavior

Source node is 'dmsehuang@yahoo.com'.

### Actual behavior

Source nodes are: '(e.g' and 'dmsehuang@yahoo.com)'

**Comment by wooorm** [comment]
Thanks, found ’em and fixed!
